### ISSUE TITLE
unclear about variable “constraint” in class CamRest676Reader in reader.py

### ISSUE THREAD

**Issue by luweishuang** [AuCson/SEDST#2]
in reader.py,   class CamRest676Reader, i found the constraint variable in tokenized_dial only contain the inform slot but no request slot,  that's different from the same file in project "sequicity", is there some reason to do like so?

**Comment by AuCson** [comment]
Thanks for your question. Yes, that's correct. That is because requestable slots do not participate directly in any metrics (in both work).
