### ISSUE TITLE
Minor mistake with Evaluator.

### ISSUE THREAD

**Issue by shizhediao** [AuCson/SEDST#3]
In semi_sup_model.py, Line 153,
`ev = CamRestEvaluator(cfg.result_path)`
I think it should be:
`        if self.dataset == 'camrest':`
`            ev = CamRestEvaluator(cfg.result_path)`
 `       elif self.dataset == 'kvret':`
  `          ev = KvretEvaluator(cfg.result_path)`

Am I right?

**Comment by AuCson** [comment]
Thank you! I will fix it soon.
